apiVersion: v1
kind: Service
metadata:
  name: techchallenge-microservico-producao
spec:
  selector:
    app: techchallenge-microservico-producao
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: localstack
# spec:
#   selector:
#     app: localstack
#   ports:
#     - protocol: TCP
#       port: 4566
#       targetPort: 4566
#   type: NodePort
